### ISSUE TITLE
Animations in wallet connection flow

### ISSUE THREAD

**Issue by creed-victor** [DistributedCollective/sovryn-monorepo#5]
Add transitions and animations for react-wallet package.

> Task will need @t-z-u to add video and maybe description.

**Comment by t-z-u** [comment]
@creed-victor could we add this to the sprint board?

**Comment by grinry** [comment]
> @creed-victor could we add this to the sprint board?

Maybe for next sprint, this one already is fulll. Unless you need it to be available as dependency?

**Comment by t-z-u** [comment]
no animations are def nice to have
